using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Shared.IoC;
using System;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.APC;
using Content.Shared.Power.Components;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using TableContainer = Content.Client.UserInterface.Controls.TableContainer;

namespace Content.Client.Power.APC.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ApcMenu : FancyWindow
    {
        public event Action? OnBreaker;
        public event Action<ApcPowerPriority, ApcPowerPriorityOverride>? OnTierOverride;

        private readonly List<(Label Req, Label Eff, Label State, OptionButton Override)> _tierRows = new();

        private bool _hasAccess;

        public ApcMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            BreakerButton.OnPressed += _ => OnBreaker?.Invoke();
        }

        public void SetEntity(EntityUid entity)
        {
            EntityView.SetEntity(entity);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ApcBoundInterfaceState) state;

            BreakerButton.Pressed = castState.MainBreaker;

            if (PowerLabel != null)
            {
                if (castState.Tripped)
                {
                    PowerLabel.Text = Loc.GetString("apc-menu-power-state-label-tripped");
                }
                else
                {
                    PowerLabel.Text = Loc.GetString("apc-menu-power-state-label-text", ("power", castState.Power), ("maxLoad", castState.MaxLoad));
                }
            }

            if (ExternalPowerStateLabel != null)
            {
                switch (castState.ApcExternalPower)
                {
                    case ApcExternalPowerState.None:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-none");
                        ExternalPowerStateLabel.SetOnlyStyleClass("negative");
                        break;
                    case ApcExternalPowerState.Low:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-low");
                        ExternalPowerStateLabel.SetOnlyStyleClass("highlight");
                        break;
                    case ApcExternalPowerState.Good:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-good");
                        ExternalPowerStateLabel.SetOnlyStyleClass("positive");
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (ChargeBar != null)
            {
                ChargeBar.Value = castState.Charge;
                UpdateChargeBarColor(castState.Charge);
                var chargePercentage = (castState.Charge / ChargeBar.MaxValue);
                ChargePercentage.Text = Loc.GetString("apc-menu-charge-label",("percent",  chargePercentage.ToString("P0")));
            }

            UpdateTierRows(castState);
        }

        private void UpdateTierRows(ApcBoundInterfaceState state)
        {
            if (_tierRows.Count != state.Tiers.Length)
                RebuildTierRows(state);
            else
                RefreshTierValues(state);
        }

        private void RebuildTierRows(ApcBoundInterfaceState state)
        {
            TierContainer.RemoveAllChildren();
            _tierRows.Clear();

            TierContainer.AddChild(new Label
            {
                Text = Loc.GetString("apc-menu-tiers-heading"),
                StyleClasses = { "LabelHeading" },
            });

            var table = new TableContainer { Columns = 5, HorizontalExpand = true };
            table.AddChild(new Label { Text = Loc.GetString("apc-menu-tiers-col-tier") });
            table.AddChild(new Label { Text = Loc.GetString("apc-menu-tiers-col-req") });
            table.AddChild(new Label { Text = Loc.GetString("apc-menu-tiers-col-eff") });
            table.AddChild(new Label { Text = Loc.GetString("apc-menu-tiers-col-state") });
            table.AddChild(new Label { Text = Loc.GetString("apc-menu-tiers-col-override") });

            foreach (var tier in state.Tiers)
            {
                var reqLabel = new Label { Text = MathF.Ceiling(tier.RequestedPower).ToString() };
                var effLabel = new Label { Text = MathF.Ceiling(tier.EffectivePower).ToString() };
                var stateLabel = new Label { Text = $"{ApcPowerTierLoc.State(tier.State)} {tier.ShedRatio:P0}" };

                var overrideButton = new OptionButton();
                overrideButton.AddItem(Loc.GetString("apc-menu-tiers-override-auto"), (int) ApcPowerPriorityOverride.Auto);
                overrideButton.AddItem(Loc.GetString("apc-menu-tiers-override-force-on"), (int) ApcPowerPriorityOverride.ForceOn);
                overrideButton.AddItem(Loc.GetString("apc-menu-tiers-override-force-off"), (int) ApcPowerPriorityOverride.ForceOff);
                overrideButton.SelectId((int) tier.Override);
                ApplyAccess(overrideButton);
                var priority = tier.Priority;
                overrideButton.OnItemSelected += args => OnTierOverride?.Invoke(priority, (ApcPowerPriorityOverride) args.Id);

                table.AddChild(new Label { Text = ApcPowerTierLoc.Priority(tier.Priority) });
                table.AddChild(reqLabel);
                table.AddChild(effLabel);
                table.AddChild(stateLabel);
                table.AddChild(overrideButton);

                _tierRows.Add((reqLabel, effLabel, stateLabel, overrideButton));
            }

            TierContainer.AddChild(table);
        }

        private void RefreshTierValues(ApcBoundInterfaceState state)
        {
            for (var i = 0; i < state.Tiers.Length; i++)
            {
                var tier = state.Tiers[i];
                var (req, eff, stateLabel, overrideBtn) = _tierRows[i];
                req.Text = MathF.Ceiling(tier.RequestedPower).ToString();
                eff.Text = MathF.Ceiling(tier.EffectivePower).ToString();
                stateLabel.Text = $"{ApcPowerTierLoc.State(tier.State)} {tier.ShedRatio:P0}";
                overrideBtn.SelectId((int) tier.Override);
            }
        }

        public void SetAccessEnabled(bool hasAccess)
        {
            _hasAccess = hasAccess;

            BreakerButton.Disabled = !hasAccess;
            BreakerButton.ToolTip = hasAccess ? null : Loc.GetString("apc-component-insufficient-access");

            // Tier rows may be rebuilt after this call, so RebuildTierRows re-applies access too.
            foreach (var (_, _, _, overrideBtn) in _tierRows)
                ApplyAccess(overrideBtn);
        }

        private void ApplyAccess(OptionButton overrideButton)
        {
            overrideButton.Disabled = !_hasAccess;
            overrideButton.ToolTip = _hasAccess ? null : Loc.GetString("apc-component-insufficient-access");
        }

        private void UpdateChargeBarColor(float charge)
        {
            if (ChargeBar == null)
            {
                return;
            }

            var normalizedCharge = charge / ChargeBar.MaxValue;

            const float leftHue = 0.0f; // Red
            const float middleHue = 0.066f; // Orange
            const float rightHue = 0.33f; // Green
            const float saturation = 1.0f; // Uniform saturation
            const float value = 0.8f; // Uniform value / brightness
            const float alpha = 1.0f; // Uniform alpha

            // These should add up to 1.0 or your transition won't be smooth
            const float leftSideSize = 0.5f; // Fraction of ChargeBar lerped from leftHue to middleHue
            const float rightSideSize = 0.5f; // Fraction of ChargeBar lerped from middleHue to rightHue

            float finalHue;
            if (normalizedCharge <= leftSideSize)
            {
                normalizedCharge /= leftSideSize; // Adjust range to 0.0 to 1.0
                finalHue = MathHelper.Lerp(leftHue, middleHue, normalizedCharge);
            }
            else
            {
                normalizedCharge = (normalizedCharge - leftSideSize) / rightSideSize; // Adjust range to 0.0 to 1.0.
                finalHue = MathHelper.Lerp(middleHue, rightHue, normalizedCharge);
            }

            // Check if null first to avoid repeatedly creating this.
            ChargeBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();

            var foregroundStyleBoxOverride = (StyleBoxFlat) ChargeBar.ForegroundStyleBoxOverride;
            foregroundStyleBoxOverride.BackgroundColor =
                Color.FromHsv(new Vector4(finalHue, saturation, value, alpha));
        }
    }
}
