using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Shared.IoC;
using System;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.APC;
using Content.Shared.Power.Components;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Power.APC.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ApcMenu : FancyWindow
    {
        public event Action? OnBreaker;
        public event Action<ApcPowerPriority, ApcPowerPriorityOverride>? OnTierOverride;

        public ApcMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            BreakerButton.OnPressed += _ => OnBreaker?.Invoke();
        }

        public void SetEntity(EntityUid entity)
        {
            EntityView.SetEntity(entity);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ApcBoundInterfaceState) state;

            BreakerButton.Pressed = castState.MainBreaker;

            if (PowerLabel != null)
            {
                if (castState.Tripped)
                {
                    PowerLabel.Text = Loc.GetString("apc-menu-power-state-label-tripped");
                }
                else
                {
                    PowerLabel.Text = Loc.GetString("apc-menu-power-state-label-text", ("power", castState.Power), ("maxLoad", castState.MaxLoad));
                }
            }

            if (ExternalPowerStateLabel != null)
            {
                switch (castState.ApcExternalPower)
                {
                    case ApcExternalPowerState.None:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-none");
                        ExternalPowerStateLabel.SetOnlyStyleClass("negative");
                        break;
                    case ApcExternalPowerState.Low:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-low");
                        ExternalPowerStateLabel.SetOnlyStyleClass("highlight");
                        break;
                    case ApcExternalPowerState.Good:
                        ExternalPowerStateLabel.Text = Loc.GetString("apc-menu-power-state-good");
                        ExternalPowerStateLabel.SetOnlyStyleClass("positive");
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (ChargeBar != null)
            {
                ChargeBar.Value = castState.Charge;
                UpdateChargeBarColor(castState.Charge);
                var chargePercentage = (castState.Charge / ChargeBar.MaxValue);
                ChargePercentage.Text = Loc.GetString("apc-menu-charge-label",("percent",  chargePercentage.ToString("P0")));
            }

            UpdateTierRows(castState);
        }

        private void UpdateTierRows(ApcBoundInterfaceState state)
        {
            TierContainer.RemoveAllChildren();

            TierContainer.AddChild(new Label
            {
                Text = "Load tiers",
                StyleClasses = { "LabelHeading" },
            });

            var header = new GridContainer { Columns = 5, HorizontalExpand = true };
            header.AddChild(new Label { Text = "Tier", MinWidth = 90 });
            header.AddChild(new Label { Text = "Req W", MinWidth = 64 });
            header.AddChild(new Label { Text = "Eff W", MinWidth = 64 });
            header.AddChild(new Label { Text = "State", MinWidth = 78 });
            header.AddChild(new Label { Text = "Override", MinWidth = 140 });
            TierContainer.AddChild(header);

            foreach (var tier in state.Tiers)
            {
                var row = new GridContainer { Columns = 5, HorizontalExpand = true };
                row.AddChild(new Label { Text = tier.Priority.ToString(), MinWidth = 90 });
                row.AddChild(new Label { Text = MathF.Ceiling(tier.RequestedPower).ToString(), MinWidth = 64 });
                row.AddChild(new Label { Text = MathF.Ceiling(tier.EffectivePower).ToString(), MinWidth = 64 });
                row.AddChild(new Label { Text = $"{tier.State} {tier.ShedRatio:P0}", MinWidth = 78 });

                var overrideButton = new OptionButton { MinWidth = 140 };
                overrideButton.AddItem("Auto", (int) ApcPowerPriorityOverride.Auto);
                overrideButton.AddItem("Force On", (int) ApcPowerPriorityOverride.ForceOn);
                overrideButton.AddItem("Force Off", (int) ApcPowerPriorityOverride.ForceOff);
                overrideButton.SelectId((int) tier.Override);
                var priority = tier.Priority;
                overrideButton.OnItemSelected += args =>
                {
                    var selected = (ApcPowerPriorityOverride) args.Id;
                    overrideButton.SelectId(args.Id);
                    OnTierOverride?.Invoke(priority, selected);
                };
                row.AddChild(overrideButton);

                TierContainer.AddChild(row);
            }
        }

        public void SetAccessEnabled(bool hasAccess)
        {
            if(hasAccess)
            {
                BreakerButton.Disabled = false;
                BreakerButton.ToolTip = null;
            }
            else
            {
                BreakerButton.Disabled = true;
                BreakerButton.ToolTip = Loc.GetString("apc-component-insufficient-access");
            }
        }

        private void UpdateChargeBarColor(float charge)
        {
            if (ChargeBar == null)
            {
                return;
            }

            var normalizedCharge = charge / ChargeBar.MaxValue;

            const float leftHue = 0.0f; // Red
            const float middleHue = 0.066f; // Orange
            const float rightHue = 0.33f; // Green
            const float saturation = 1.0f; // Uniform saturation
            const float value = 0.8f; // Uniform value / brightness
            const float alpha = 1.0f; // Uniform alpha

            // These should add up to 1.0 or your transition won't be smooth
            const float leftSideSize = 0.5f; // Fraction of ChargeBar lerped from leftHue to middleHue
            const float rightSideSize = 0.5f; // Fraction of ChargeBar lerped from middleHue to rightHue

            float finalHue;
            if (normalizedCharge <= leftSideSize)
            {
                normalizedCharge /= leftSideSize; // Adjust range to 0.0 to 1.0
                finalHue = MathHelper.Lerp(leftHue, middleHue, normalizedCharge);
            }
            else
            {
                normalizedCharge = (normalizedCharge - leftSideSize) / rightSideSize; // Adjust range to 0.0 to 1.0.
                finalHue = MathHelper.Lerp(middleHue, rightHue, normalizedCharge);
            }

            // Check if null first to avoid repeatedly creating this.
            ChargeBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();

            var foregroundStyleBoxOverride = (StyleBoxFlat) ChargeBar.ForegroundStyleBoxOverride;
            foregroundStyleBoxOverride.BackgroundColor =
                Color.FromHsv(new Vector4(finalHue, saturation, value, alpha));
        }
    }
}
